services:
  streamlit:
    container_name: noaa-streamlit
    restart: always
    build: 
      context: .
      dockerfile: docker/streamlit/Dockerfile
    ports:
      - '8501:8501'
    volumes:
      - ./data:/noaa_app/data
      - ./app:/noaa_app/app
      - ./.streamlit:/noaa_app/.streamlit
    networks:
      - nginx_proxy_manager_default
  prefect:
    container_name: noaa-prefect
    restart: always
    build: 
      context: .
      dockerfile: docker/prefect/Dockerfile
    ports:
      - '4200:4200'
    environment:
      - DBT_PROFILES_DIR=/noaa_app/.dbt
    volumes:
      - ./data:/noaa_app/data
      - ./prefect_flows:/noaa_app/prefect_flows
      - ./dbt_transforms:/noaa_app/dbt_transforms
      - ./.dbt:/noaa_app/.dbt
  dbt:
    container_name: noaa-dbt
    restart: always
    build: 
      context: .
      dockerfile: docker/dbt/Dockerfile
    ports:
      - '8080:8080'
    environment:
      - DBT_PROFILES_DIR=/noaa_app/.dbt
    volumes:
      - ./data:/noaa_app/data
      - ./dbt_transforms:/noaa_app/dbt_transforms
      - ./.dbt:/noaa_app/.dbt

networks:
  nginx_proxy_manager_default:
    external: true