services:
  app:
    container_name: noaa-app
    build: .
    network_mode: "host"
    environment:
      - DBT_PROFILES_DIR=/app/.dbt
    volumes:
      - ./prefect_flows:/app/prefect_flows
      - ./dbt_transforms:/app/dbt_transforms
      - ./app:/app/app
      - ./.dbt:/app/.dbt